package tunnel

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	GlobalConfigDir  = "/etc/dnstm"
	GlobalConfigFile = "dnstm.conf"
)

// GlobalConfig stores the global dnstm configuration.
type GlobalConfig struct {
	ActiveProvider ProviderType
}

// LoadGlobalConfig loads the global configuration.
func LoadGlobalConfig() (*GlobalConfig, error) {
	configPath := filepath.Join(GlobalConfigDir, GlobalConfigFile)

	file, err := os.Open(configPath)
	if err != nil {
		if os.IsNotExist(err) {
			// Return default config
			return &GlobalConfig{
				ActiveProvider: ProviderDNSTT, // Default to DNSTT for backward compat
			}, nil
		}
		return nil, err
	}
	defer file.Close()

	config := &GlobalConfig{}

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.Trim(strings.TrimSpace(parts[1]), "\"")

		switch key {
		case "ACTIVE_PROVIDER":
			config.ActiveProvider = ProviderType(value)
		}
	}

	return config, scanner.Err()
}

// SaveGlobalConfig saves the global configuration.
func SaveGlobalConfig(cfg *GlobalConfig) error {
	if err := os.MkdirAll(GlobalConfigDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	configPath := filepath.Join(GlobalConfigDir, GlobalConfigFile)

	content := fmt.Sprintf(`# dnstm global configuration
# Generated by dnstm

ACTIVE_PROVIDER="%s"
`, cfg.ActiveProvider)

	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// GlobalConfigExists checks if the global config file exists.
func GlobalConfigExists() bool {
	configPath := filepath.Join(GlobalConfigDir, GlobalConfigFile)
	_, err := os.Stat(configPath)
	return err == nil
}

// GetActiveProvider returns the currently active provider.
func GetActiveProvider() (Provider, error) {
	cfg, err := LoadGlobalConfig()
	if err != nil {
		return nil, err
	}

	return Get(cfg.ActiveProvider)
}

// SetActiveProvider sets the active provider.
func SetActiveProvider(pt ProviderType) error {
	cfg := &GlobalConfig{
		ActiveProvider: pt,
	}
	return SaveGlobalConfig(cfg)
}

// RemoveGlobalConfig removes the global config directory.
func RemoveGlobalConfig() {
	os.RemoveAll(GlobalConfigDir)
}
