package dnstt

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	ConfigDir   = "/etc/dnstt"
	ConfigFile  = "dnstt-server.conf"
	Port        = "5300"
	ReleaseURL  = "https://github.com/net2share/dnstt/releases/download/latest"
	BinaryName  = "dnstt-server"
	ServiceName = "dnstt-server"
	ServiceUser = "dnstt"
)

// Config holds the DNSTT server configuration.
type Config struct {
	NSSubdomain      string
	MTU              string
	TunnelMode       string
	MTProxySecret    string
	PrivateKeyFile   string
	PublicKeyFile    string
	TargetPort       string
	SSHTunnelEnabled string // "true" or "false" - tracks if SSH tunnel hardening is applied
}

// Load loads the DNSTT configuration from file.
func Load() (*Config, error) {
	configPath := filepath.Join(ConfigDir, ConfigFile)

	file, err := os.Open(configPath)
	if err != nil {
		if os.IsNotExist(err) {
			return &Config{
				MTU:        "1232",
				TunnelMode: "ssh",
			}, nil
		}
		return nil, err
	}
	defer file.Close()

	config := &Config{
		MTU:        "1232",
		TunnelMode: "ssh",
	}

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.Trim(strings.TrimSpace(parts[1]), "\"")

		switch key {
		case "NS_SUBDOMAIN":
			config.NSSubdomain = value
		case "MTU_VALUE":
			config.MTU = value
		case "TUNNEL_MODE":
			config.TunnelMode = value
		case "PRIVATE_KEY_FILE":
			config.PrivateKeyFile = value
		case "PUBLIC_KEY_FILE":
			config.PublicKeyFile = value
		case "TARGET_PORT":
			config.TargetPort = value
		case "SSH_TUNNEL_ENABLED":
			config.SSHTunnelEnabled = value
		case "MTPROXY_SECRET":
			config.MTProxySecret = value
		}
	}

	return config, scanner.Err()
}

// Save saves the DNSTT configuration to file.
func (c *Config) Save() error {
	if err := os.MkdirAll(ConfigDir, 0750); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	configPath := filepath.Join(ConfigDir, ConfigFile)

	content := fmt.Sprintf(`# dnstt-server configuration
# Generated by dnstm

NS_SUBDOMAIN="%s"
MTU_VALUE="%s"
TUNNEL_MODE="%s"
PRIVATE_KEY_FILE="%s"
PUBLIC_KEY_FILE="%s"
TARGET_PORT="%s"
SSH_TUNNEL_ENABLED="%s"
`, c.NSSubdomain, c.MTU, c.TunnelMode, c.PrivateKeyFile, c.PublicKeyFile, c.TargetPort, c.SSHTunnelEnabled)
	// Add MTProxy secret if in mtproto mode
	if c.TunnelMode == "mtproto" && c.MTProxySecret != "" {
		content += fmt.Sprintf(`MTPROXY_SECRET="%s"
`, c.MTProxySecret)
	}
	if err := os.WriteFile(configPath, []byte(content), 0640); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// Exists checks if the DNSTT configuration exists.
func Exists() bool {
	configPath := filepath.Join(ConfigDir, ConfigFile)
	_, err := os.Stat(configPath)
	return err == nil
}

// GetKeyFilenames returns the private and public key file paths for a subdomain.
func GetKeyFilenames(subdomain string) (privateKey, publicKey string) {
	sanitized := strings.ReplaceAll(subdomain, ".", "_")
	privateKey = filepath.Join(ConfigDir, sanitized+"_server.key")
	publicKey = filepath.Join(ConfigDir, sanitized+"_server.pub")
	return
}

// RemoveAll removes the DNSTT configuration directory.
func RemoveAll() {
	os.RemoveAll(ConfigDir)
}

// GetFormattedConfig returns the configuration as a formatted string for display.
func (c *Config) GetFormattedConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("NS Subdomain:    %s\n", c.NSSubdomain))
	b.WriteString(fmt.Sprintf("Tunnel Mode:     %s\n", c.TunnelMode))
	b.WriteString(fmt.Sprintf("MTU:             %s\n", c.MTU))
	b.WriteString(fmt.Sprintf("Target Port:     %s\n", c.TargetPort))
	b.WriteString(fmt.Sprintf("Private Key:     %s\n", c.PrivateKeyFile))
	b.WriteString(fmt.Sprintf("Public Key File: %s\n", c.PublicKeyFile))
	return b.String()
}
