package proxy

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/net2share/go-corelib/osdetect"
)

const (
	DanteConfigPath = "/etc/danted.conf"
	DanteService    = "danted"
)

func InstallDante(pkgManager string) error {
	var cmd *exec.Cmd

	switch pkgManager {
	case "apt":
		cmd = exec.Command("apt", "install", "-y", "dante-server")
	case "dnf":
		cmd = exec.Command("dnf", "install", "-y", "dante-server")
	case "yum":
		cmd = exec.Command("yum", "install", "-y", "dante-server")
	default:
		return fmt.Errorf("unsupported package manager: %s", pkgManager)
	}

	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to install dante-server: %s: %w", string(output), err)
	}

	return nil
}

func ConfigureDante() error {
	iface, err := osdetect.GetDefaultInterface()
	if err != nil || iface == "" {
		iface = "eth0"
	}

	config := fmt.Sprintf(`# Dante SOCKS5 proxy configuration
# Generated by dnstm

logoutput: syslog

internal: 127.0.0.1 port = 1080

external: %s

socksmethod: none
clientmethod: none

user.privileged: root
user.notprivileged: nobody

client pass {
    from: 127.0.0.0/8 to: 0.0.0.0/0
    log: error
}

socks pass {
    from: 127.0.0.0/8 to: 0.0.0.0/0
    protocol: tcp udp
    log: error
}
`, iface)

	if err := os.WriteFile(DanteConfigPath, []byte(config), 0644); err != nil {
		return fmt.Errorf("failed to write dante config: %w", err)
	}

	return nil
}

func StartDante() error {
	exec.Command("systemctl", "enable", DanteService).Run()

	cmd := exec.Command("systemctl", "start", DanteService)
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to start dante: %s: %w", string(output), err)
	}

	return nil
}

func RestartDante() error {
	cmd := exec.Command("systemctl", "restart", DanteService)
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to restart dante: %s: %w", string(output), err)
	}
	return nil
}

func IsDanteInstalled() bool {
	paths := []string{
		"/usr/sbin/danted",
		"/usr/bin/danted",
	}

	for _, path := range paths {
		if _, err := os.Stat(path); err == nil {
			return true
		}
	}

	return false
}

func IsDanteRunning() bool {
	cmd := exec.Command("systemctl", "is-active", DanteService)
	output, _ := cmd.Output()
	return strings.TrimSpace(string(output)) == "active"
}
