package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	ConfigDir  = "/etc/dnstt"
	ConfigFile = "dnstt-server.conf"
	DnsttPort  = "5300"
)

type Config struct {
	NSSubdomain    string
	MTU            string
	TunnelMode     string
	PrivateKeyFile string
	PublicKeyFile  string
	TargetPort     string
}

func Load() (*Config, error) {
	configPath := filepath.Join(ConfigDir, ConfigFile)

	file, err := os.Open(configPath)
	if err != nil {
		if os.IsNotExist(err) {
			return &Config{
				MTU:        "1232",
				TunnelMode: "ssh",
			}, nil
		}
		return nil, err
	}
	defer file.Close()

	config := &Config{
		MTU:        "1232",
		TunnelMode: "ssh",
	}

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.Trim(strings.TrimSpace(parts[1]), "\"")

		switch key {
		case "NS_SUBDOMAIN":
			config.NSSubdomain = value
		case "MTU_VALUE":
			config.MTU = value
		case "TUNNEL_MODE":
			config.TunnelMode = value
		case "PRIVATE_KEY_FILE":
			config.PrivateKeyFile = value
		case "PUBLIC_KEY_FILE":
			config.PublicKeyFile = value
		case "TARGET_PORT":
			config.TargetPort = value
		}
	}

	return config, scanner.Err()
}

func (c *Config) Save() error {
	if err := os.MkdirAll(ConfigDir, 0750); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	configPath := filepath.Join(ConfigDir, ConfigFile)

	content := fmt.Sprintf(`# dnstt-server configuration
# Generated by dnstm

NS_SUBDOMAIN="%s"
MTU_VALUE="%s"
TUNNEL_MODE="%s"
PRIVATE_KEY_FILE="%s"
PUBLIC_KEY_FILE="%s"
TARGET_PORT="%s"
`, c.NSSubdomain, c.MTU, c.TunnelMode, c.PrivateKeyFile, c.PublicKeyFile, c.TargetPort)

	if err := os.WriteFile(configPath, []byte(content), 0640); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

func Exists() bool {
	configPath := filepath.Join(ConfigDir, ConfigFile)
	_, err := os.Stat(configPath)
	return err == nil
}

func GetKeyFilenames(subdomain string) (privateKey, publicKey string) {
	sanitized := strings.ReplaceAll(subdomain, ".", "_")
	privateKey = filepath.Join(ConfigDir, sanitized+"_server.key")
	publicKey = filepath.Join(ConfigDir, sanitized+"_server.pub")
	return
}
