package slipstream

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/net2share/dnstm/internal/system"
)

const (
	ConfigDir   = "/etc/slipstream"
	ConfigFile  = "slipstream-server.conf"
	Port        = "5301"
	ReleaseURL  = "https://github.com/net2share/slipstream-rust-build/releases/download/latest"
	BinaryName  = "slipstream-server"
	ServiceName = "slipstream-server"
	ServiceUser = system.DnstmUser
)

// Config holds the Slipstream server configuration.
type Config struct {
	Domain           string
	DNSListenPort    string
	TargetAddress    string
	CertFile         string
	KeyFile          string
	TunnelMode       string
	TargetPort       string
	SSHTunnelEnabled string
	MTProxySecret    string
}

// Load loads the Slipstream configuration from file.
func Load() (*Config, error) {
	configPath := filepath.Join(ConfigDir, ConfigFile)

	file, err := os.Open(configPath)
	if err != nil {
		if os.IsNotExist(err) {
			return &Config{
				DNSListenPort: Port,
				TunnelMode:    "ssh",
			}, nil
		}
		return nil, err
	}
	defer file.Close()

	config := &Config{
		DNSListenPort: Port,
		TunnelMode:    "ssh",
	}

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.Trim(strings.TrimSpace(parts[1]), "\"")

		switch key {
		case "DOMAIN":
			config.Domain = value
		case "DNS_LISTEN_PORT":
			config.DNSListenPort = value
		case "TARGET_ADDRESS":
			config.TargetAddress = value
		case "CERT_FILE":
			config.CertFile = value
		case "KEY_FILE":
			config.KeyFile = value
		case "TUNNEL_MODE":
			config.TunnelMode = value
		case "TARGET_PORT":
			config.TargetPort = value
		case "SSH_TUNNEL_ENABLED":
			config.SSHTunnelEnabled = value
		case "MTPROXY_SECRET":
			config.MTProxySecret = value
		}
	}

	return config, scanner.Err()
}

// Save saves the Slipstream configuration to file.
func (c *Config) Save() error {
	if err := os.MkdirAll(ConfigDir, 0750); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	configPath := filepath.Join(ConfigDir, ConfigFile)

	content := fmt.Sprintf(`# slipstream-server configuration
# Generated by dnstm

DOMAIN="%s"
DNS_LISTEN_PORT="%s"
TARGET_ADDRESS="%s"
CERT_FILE="%s"
KEY_FILE="%s"
TUNNEL_MODE="%s"
TARGET_PORT="%s"
SSH_TUNNEL_ENABLED="%s"
`, c.Domain, c.DNSListenPort, c.TargetAddress, c.CertFile, c.KeyFile, c.TunnelMode, c.TargetPort, c.SSHTunnelEnabled)

	// Add MTProxy secret if in mtproto mode
	if c.TunnelMode == "mtproto" && c.MTProxySecret != "" {
		content += fmt.Sprintf(`MTPROXY_SECRET="%s"
`, c.MTProxySecret)
	}

	if err := os.WriteFile(configPath, []byte(content), 0640); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// Exists checks if the Slipstream configuration exists.
func Exists() bool {
	configPath := filepath.Join(ConfigDir, ConfigFile)
	_, err := os.Stat(configPath)
	return err == nil
}

// GetCertFilenames returns the certificate and key file paths for a domain.
func GetCertFilenames(domain string) (certFile, keyFile string) {
	sanitized := strings.ReplaceAll(domain, ".", "_")
	certFile = filepath.Join(ConfigDir, sanitized+"_cert.pem")
	keyFile = filepath.Join(ConfigDir, sanitized+"_key.pem")
	return
}

// RemoveAll removes the Slipstream configuration directory.
func RemoveAll() {
	os.RemoveAll(ConfigDir)
}

// GetFormattedConfig returns the configuration as a formatted string for display.
func (c *Config) GetFormattedConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("Domain:          %s\n", c.Domain))
	b.WriteString(fmt.Sprintf("Tunnel Mode:     %s\n", c.TunnelMode))
	b.WriteString(fmt.Sprintf("DNS Listen Port: %s\n", c.DNSListenPort))
	b.WriteString(fmt.Sprintf("Target Address:  %s\n", c.TargetAddress))
	b.WriteString(fmt.Sprintf("Certificate:     %s\n", c.CertFile))
	b.WriteString(fmt.Sprintf("Key File:        %s\n", c.KeyFile))
	return b.String()
}
